-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ',U.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(U.TLNO,1,3),'-', SUBSTRING(U.TLNO,4,4),'-',SUBSTRING(U.TLNO,8)) AS '전화번호' -- SUBSTRING(문자열, 시작위치, 길이)
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
AND B.WRITER_ID IN (SELECT WRITER_ID
                   FROM USED_GOODS_BOARD
                   GROUP BY WRITER_ID
                   HAVING COUNT(*)>=3)
GROUP BY U.USER_ID
ORDER BY U.USER_ID DESC                   
