-- 코드를 작성해주세요
WITH T1 AS (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
            FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)
           )
           
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (T1.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E JOIN T1
ON YEAR(E.DIFFERENTIATION_DATE) = T1.YEAR
ORDER BY YEAR(E.DIFFERENTIATION_DATE), (T1.MAX_SIZE - E.SIZE_OF_COLONY)